name: Update Velo Counters

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 1 * *' # every 1st day of each month

jobs:
  update_counters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Update Counters Script
        run: node .github/scripts/update-velo-counters.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: '[Automatique] Mise à jour des compteurs vélo'
          title: 'Compteurs - Mise à jour automatique des compteurs vélo'
          body: 'Mise à jour automatique des compteurs via une github action.'
          base: main
          branch: update-counters-${{ github.run_id }}
          delete-branch: true
